image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git


build: false  # будем использовать свой скрипт сборки

build_script:
    - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации

notifications:
  - provider: Email
    # Список адресов
    to:
      - zybu@live.ru
    # Отправлять ли письмо в случае успеха?
    on_build_success: false
    # Отправлять ли письмо в случае провала?
    on_build_failure: true
    # Отправлять ли письмо когда статус изменился?
    on_build_status_changed: true